// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthToken struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Email     string           `json:"email"`
	Username  string           `json:"username"`
	FirstName pgtype.Text      `json:"first_name"`
	LastName  pgtype.Text      `json:"last_name"`
	IsActive  pgtype.Bool      `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
