// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, id int32) (User, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
